// Copies the built single-file app and the shared draft code into gas/ for clasp.
// Apps Script has no modules: every .js file shares one global scope, so the
// import lines are dropped and `export` keywords are stripped.
import { readFileSync, writeFileSync } from 'node:fs'

const SHARED = ['draftLogic.js', 'roster.js', 'formOptions.js', 'sampleData.js', 'views.js', 'service.js']

const parts = SHARED.map((file) => {
  const source = readFileSync(`src/shared/${file}`, 'utf8')
    .replace(/^import .*$/gm, '')
    .replace(/^export (?=(const|function|let|class) )/gm, '')
  const leftover = source.match(/^\s*(import|export)\b.*$/m)
  if (leftover) throw new Error(`src/shared/${file} has a line Apps Script can't run: ${leftover[0]}`)
  return `// ---- src/shared/${file} ----\n${source}`
})

writeFileSync('gas/Shared.js', `// Generated by scripts/build-gas.mjs from src/shared/. Do not edit.\n\n${parts.join('\n')}`)
writeFileSync('gas/index.html', readFileSync('dist-gas/index.html', 'utf8'))
console.log('Wrote gas/Shared.js and gas/index.html')
