// Copies the built single-file app and the shared draft code into gas/ for clasp.
// Apps Script has no modules: every .js file shares one global scope, so the
// import lines are dropped and `export` keywords are stripped.
import { readFileSync, writeFileSync } from 'node:fs'

const SHARED = ['draftLogic.js', 'roster.js', 'merge.js', 'formOptions.js', 'sampleData.js', 'views.js', 'service.js']

const parts = SHARED.map((file) => {
  const source = readFileSync(`src/shared/${file}`, 'utf8')
    .replace(/^import .*$/gm, '')
    .replace(/^export (?=(const|function|let|class) )/gm, '')
  const leftover = source.match(/^\s*(import|export)\b.*$/m)
  if (leftover) throw new Error(`src/shared/${file} has a line Apps Script can't run: ${leftover[0]}`)
  return `// ---- src/shared/${file} ----\n${source}`
})

// Apps Script concatenates every file into one global scope, so two shared files
// declaring the same top-level name is a syntax error that only surfaces at
// `clasp push` — after a successful build and a green test run. Catch it here.
const declared = new Map()
const clashes = []
SHARED.forEach((file, i) => {
  const names = [...parts[i].matchAll(/^(?:const|let|function|class) ([A-Za-z_$][\w$]*)/gm)].map((m) => m[1])
  for (const name of names) {
    if (declared.has(name)) clashes.push(`${name} (src/shared/${declared.get(name)} and src/shared/${file})`)
    else declared.set(name, file)
  }
})
if (clashes.length) {
  throw new Error(`Apps Script shares one global scope, so these top-level names collide:\n  ${clashes.join('\n  ')}`)
}

writeFileSync('gas/Shared.js', `// Generated by scripts/build-gas.mjs from src/shared/. Do not edit.\n\n${parts.join('\n')}`)
writeFileSync('gas/index.html', readFileSync('dist-gas/index.html', 'utf8'))
console.log('Wrote gas/Shared.js and gas/index.html')
